// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOnUnWRqs7wL-vSXuhxg6gcB-qs5nbMcE',
    appId: '1:371007706153:web:98af2baf61c4bae6e6f838',
    messagingSenderId: '371007706153',
    projectId: 'healthease-c8137',
    authDomain: 'healthease-c8137.firebaseapp.com',
    storageBucket: 'healthease-c8137.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkAbCcDMqx5qPpCOUJsFHk4p76u8-8FVs',
    appId: '1:371007706153:android:b507369283b005b8e6f838',
    messagingSenderId: '371007706153',
    projectId: 'healthease-c8137',
    storageBucket: 'healthease-c8137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChOBeXYpjc7DVHU_pMt1T-dVYV3SIixqo',
    appId: '1:371007706153:ios:9ce0b9cac38a76d5e6f838',
    messagingSenderId: '371007706153',
    projectId: 'healthease-c8137',
    storageBucket: 'healthease-c8137.firebasestorage.app',
    iosBundleId: 'com.example.healthEase',
  );
}
